/**
 * @file    main_usercode.c
 * @brief   SD Card + FatFs logging — user code for Blue Pill (STM32F103C8T6)
 *
 * Paste each labeled block into the matching USER CODE section of the
 * CubeMX-generated main.c.  Do NOT replace CubeMX-generated init calls.
 *
 * Prerequisites (CubeMX):
 *   - SPI2: Full-Duplex Master, Mode 0, 8-bit. Pins PB13/PB14/PB15.
 *   - PB12: GPIO_Output (SD CS, active-low)
 *   - FATFS middleware with SPI user driver
 *   - ADC1 Ch0 (PA0), software trigger
 *   - USART1 115200 8N1 (optional debug)
 *
 * NOTE: This code is not hardware-tested. Verify on your board.
 * NOTE: FatFs types (FATFS, FIL, FRESULT, etc.) come from "fatfs.h" / "ff.h"
 *       generated by CubeMX. Ensure FATFS middleware is enabled.
 */

// ===== USER CODE BEGIN Includes =====
#include "fatfs.h"    /* CubeMX-generated FatFs include */
#include <stdio.h>
#include <string.h>
// ===== USER CODE END Includes =====


// ===== USER CODE BEGIN PD =====
#define SD_CS_PIN      GPIO_PIN_12
#define SD_CS_PORT     GPIOB
#define LOG_FILENAME   "LOG.TXT"
#define LOG_PERIOD_MS  1000U
// ===== USER CODE END PD =====


// ===== USER CODE BEGIN PV =====
static FATFS g_fatfs;         /* Filesystem object                  */
static FIL   g_logFile;       /* File object                        */
static char  g_lineBuf[64];   /* Formatted log line buffer          */
// ===== USER CODE END PV =====


// ===== USER CODE BEGIN PFP =====
static void Error_Handler_SD(const char *context, FRESULT fr);
static void UART_Print(const char *msg);
// ===== USER CODE END PFP =====


// ===== USER CODE BEGIN 2 =====
{
    FRESULT fr;
    uint16_t bytesWritten;

    /* Ensure CS is deasserted before init */
    HAL_GPIO_WritePin(SD_CS_PORT, SD_CS_PIN, GPIO_PIN_SET);
    HAL_Delay(10);  /* let card power up */

    /* Mount the filesystem — "" maps to logical drive 0 (SD) */
    fr = f_mount(&g_fatfs, "", 1 /* immediate mount */);
    if (fr != FR_OK)
    {
        Error_Handler_SD("f_mount", fr);
    }

    /* Open (or create) the log file in append mode */
    fr = f_open(&g_logFile, LOG_FILENAME, FA_OPEN_APPEND | FA_WRITE);
    if (fr != FR_OK)
    {
        Error_Handler_SD("f_open", fr);
    }

    UART_Print("SD mount OK. Logging started.\r\n");

    /* ---- Main logging loop ---- */
    for (;;)
    {
        /* Read ADC1 Ch0 (PA0) */
        uint32_t adcRaw = 0;
        if (HAL_ADC_Start(&hadc1) == HAL_OK)
        {
            if (HAL_ADC_PollForConversion(&hadc1, 10) == HAL_OK)
            {
                adcRaw = HAL_ADC_GetValue(&hadc1);
            }
            HAL_ADC_Stop(&hadc1);
        }

        /* Build log line */
        uint32_t uptimeSec = HAL_GetTick() / 1000UL;
        int len = snprintf(g_lineBuf, sizeof(g_lineBuf),
                           "T=%lus ADC=%lu (0x%04lX)\r\n",
                           uptimeSec, adcRaw, adcRaw);

        /* Write to file */
        UINT written = 0;
        fr = f_write(&g_logFile, g_lineBuf, (UINT)len, &written);
        if (fr != FR_OK || (int)written != len)
        {
            Error_Handler_SD("f_write", fr);
        }

        /* Flush to ensure data reaches the card on power loss */
        fr = f_sync(&g_logFile);
        if (fr != FR_OK)
        {
            Error_Handler_SD("f_sync", fr);
        }

        /* Optional: echo to UART */
        UART_Print(g_lineBuf);

        HAL_Delay(LOG_PERIOD_MS);
    }

    /* Unreachable under normal operation */
    f_close(&g_logFile);
    f_mount(NULL, "", 0);
}
// ===== USER CODE END 2 =====


/* -----------------------------------------------------------------------
   Helper Functions
   ----------------------------------------------------------------------- */

// ===== USER CODE BEGIN 4 =====

/**
 * @brief Error handler for FatFs errors — blinks LED rapidly and halts.
 * @param context  Short string identifying the failing call.
 * @param fr       FatFs result code.
 */
static void Error_Handler_SD(const char *context, FRESULT fr)
{
    char msg[80];
    snprintf(msg, sizeof(msg), "[ERR] %s failed: FRESULT=%d\r\n", context, (int)fr);
    UART_Print(msg);

    /* Blink onboard LED (PC13, active-low) rapidly to indicate error */
    while (1)
    {
        HAL_GPIO_WritePin(GPIOC, GPIO_PIN_13, GPIO_PIN_RESET); /* LED ON  */
        HAL_Delay(100);
        HAL_GPIO_WritePin(GPIOC, GPIO_PIN_13, GPIO_PIN_SET);   /* LED OFF */
        HAL_Delay(100);
    }
}

/**
 * @brief Blocking UART1 transmit helper.
 */
static void UART_Print(const char *msg)
{
    /* huart1 declared extern in main.h by CubeMX */
    HAL_UART_Transmit(&huart1, (const uint8_t *)msg, (uint16_t)strlen(msg), 200);
}

/* -----------------------------------------------------------------------
   SPI CS Control (called by FatFs SPI driver if using CubeMX template)
   These functions may already exist in the CubeMX-generated user_diskio.c.
   Add them there if the template does not provide them.
   ----------------------------------------------------------------------- */

/**
 * @brief Assert SD CS (active-low).
 */
void SD_CS_Select(void)
{
    HAL_GPIO_WritePin(SD_CS_PORT, SD_CS_PIN, GPIO_PIN_RESET);
}

/**
 * @brief Deassert SD CS.
 */
void SD_CS_Deselect(void)
{
    HAL_GPIO_WritePin(SD_CS_PORT, SD_CS_PIN, GPIO_PIN_SET);
}

// ===== USER CODE END 4 =====
